# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d0ff0833bff079944020307cbc316ac1694b61c91a41d5aa9326b634af701ff284e1edacec71260d62ced7938957cac28967a2dd9c951dde3489126ba09d20a

test:
  secret_key_base: a08b3d4eb0774ad8f37337e3d53bc509d5715be6175715e0cac9341f24d2645b2a64b4838da664e259305f93af6834d8b2013a505531cd575e687549dda99260

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
